import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { theme, ConfigProvider } from "antd";
import {
  ClerkProvider
} from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
      <AntdRegistry>
      <ConfigProvider
        theme={{
          cssVar: true, hashed: false,
          token: {
            colorTextSecondary: '#fffff',
          }
        }}
      >
      {children}
      </ConfigProvider>
      </AntdRegistry>
      </body>
    </html>
    </ClerkProvider>
  );
}
